name: Create new release

on:
    push:
        branches:
            - main
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Set git username and email
              run: |
                  git config --global user.email ${{ github.actor }}@users.noreply.github.com
                  git config --global user.name ${{ github.actor }}
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@janziemba'
            - name: Fetch tags
              run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
            - name: Authenticate with the GitHub Package Registry
              run: echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >
                  ~/.npmrc
            - name: Install dependencies
              run: yarn install --network-timeout 100000 --network-concurrency 1
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Release packages
              run: npx lerna publish --yes
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Release
              run: yarn semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  HUSKY: 0
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
